
export const FETCH_BLOGS = 'FETCH_BLOGS'
export const ADD_BLOG = 'ADD_BLOG'
export const LIKE_BLOG = 'LIKE_BLOG'
export const REMOVE_BLOG = 'REMOVE_BLOG'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'


export const LOGIN = 'LOGIN'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const LOGOUT = 'LOGOUT'